[package]
name = "book-of-stars"
version = "0.1.0"
authors = ["hyena <hyena@users.noreply.github.com>"]

[dependencies]
hyper = "0.9.14"
lazy_static = "0.1.*"
regex = "0.1"
rocket = "0.1.2"
rocket_codegen = "0.1.2"
rustc-serialize = "0.3"
slack_api = "0.15.0"
toml = "0.2"
